[package]
name = "fathers-day-2020"
version = "0.1.0"
authors = ["ComprosoftCEO"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rl-sys = "0.5.2"
lazy_static = "1.4.0"
